### PR TITLE
Fix postcss 8.x compatibility

### LINKED ISSUE #344: PostCSS 8 compatibility
My `rfs` package is at version 9.0.3. 

I updated PostCSS to version 8 and this is the error I am getting : 

```
postcss-rfs: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
```
I guess it's referring to this  :
https://github.com/twbs/rfs/blob/1a22aa714f20c4268b722319b2b83c0067d290e3/postcss.js#L17

Is it planned to support PostCSS 8 in the near future?

### PR DESCRIPTION
**Pull request by c0rdyc3p5**
Update postcss to be compatible with version 8, options are now useable too.

Fixes #344

### CODE REVIEW

**Comment by SimonDesautels** [comment]
This might fix #344

**Comment by kevinaxial** [comment]
@MartijnCuppens bump

**Comment by brennanangel** [comment]
Perhaps @XhmikosR could review?

**Comment by XhmikosR** [comment]
Please revert any unrelated changes and keep only the minimum ones needed to fix the problem.

**Comment by XhmikosR** [comment]
Hey!

I was notified, but my concern is that it seems our tests don't cover everything. :/ I mean, shouldn't the existent tests be broken on main already?

Also, looking at https://evilmartians.com/chronicles/postcss-8-plugin-migration it seems to list more changes.

**Comment by c0rdyc3p5** [comment]
@XhmikosR  Yo ! Just checked the other change needed in the post. By the way, no the library still works perfectly fine for now, it seems like postcss don't break yet, but with my changes postcss won't output a message error neither. My fix was really just to use the 'new' way and remove the deprecation message from postcss because in fact, it is 'not' broken, it is still just a 'deprecation notice'. When I get free time I'll check to add the others change if they apply :)

**Review by XhmikosR — APPROVED** [review]

**Comment by c0rdyc3p5** [comment]
@XhmikosR hi ! Do you have an idea when the changes will roll into a new release ? So we can update our npm package ?

**Comment by XhmikosR** [comment]
Not sure TBH, because it's been too long and I don't even recall the changed compared to 9.x.

/CC @mdo we might need to prioritize this and I can cut a v10 with what we have now. I just need help with the release notes (apart from postcss 8.x support)

**Comment by cfxd** [comment]
@XhmikosR any update on when this will be released? Just would love to get it working with PostCss 8.x! Please lmk if there's anything I can do to get a release out there!

**Comment by XhmikosR** [comment]
Sorry for the so late reply. So, I'd like to tackle this for main at least.

That being said, I don't even recall the current main changes plus it seems we don't list `postcss` in `peerDependencies` but that's how it is since even AFAICT.

I'll try to cut a new major release in the next days from main, but the other older versions will be left as is.

**Comment by XhmikosR** [comment]
I pushed a few updates and now only the release notes are left to handle. Hopefully I'll get some help and cut v10 major release today/tomorrow.

**Comment by XhmikosR** [comment]
Just released v10 https://github.com/twbs/rfs/releases/tag/v10.0.0

The release notes are far from perfect, so if anyone has any suggestions let me know.

**Pull request merged**
