### PR TITLE
Regenerate package-lock.json

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
We are now down to 5 vulnerabilities:

```
C:\Users\xmr\Desktop\rfs>npm audit

                       === npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  Moderate        Prototype Pollution

  Package         minimist

  Patched in      >=1.2.3

  Dependency of   gulp [dev]

  Path            gulp > glob-watcher > chokidar > fsevents > node-pre-gyp >
                  mkdirp > minimist

  More info       https://npmjs.com/advisories/1179


  Moderate        Prototype Pollution

  Package         minimist

  Patched in      >=1.2.3

  Dependency of   gulp [dev]

  Path            gulp > glob-watcher > chokidar > fsevents > node-pre-gyp >
                  tar > mkdirp > minimist

  More info       https://npmjs.com/advisories/1179


  Moderate        Prototype Pollution

  Package         minimist

  Patched in      >=1.2.3

  Dependency of   gulp [dev]

  Path            gulp > glob-watcher > chokidar > fsevents > node-pre-gyp >
                  rc > minimist

  More info       https://npmjs.com/advisories/1179


  Moderate        Prototype Pollution

  Package         minimist

  Patched in      >=1.2.3

  Dependency of   mocha [dev]

  Path            mocha > mkdirp > minimist

  More info       https://npmjs.com/advisories/1179


  Moderate        Prototype Pollution

  Package         minimist

  Patched in      >=1.2.3

  Dependency of   stylelint [dev]

  Path            stylelint > postcss-sass > gonzales-pe > minimist

  More info       https://npmjs.com/advisories/1179

found 5 moderate severity vulnerabilities in 11497 scanned packages
  5 vulnerabilities require manual review. See the full report for details.
```

**Comment by XhmikosR** [comment]
We can wait a bit if you want. I'm sure some of the rest of the vulns will be addressed soon

**Comment by MartijnCuppens** [comment]
I don't mind waiting a bit

**Comment by XhmikosR** [comment]
I'm going to merge this since there's only one moderate vulnerability left in stylelint > postcss-sass > gonzales-pe > minimist

**Pull request merged**
