### PR TITLE
Switch to lefthook

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Ditch Husky in favor of https://github.com/Arkweid/lefthook. In the future we can split the tests more, eg. only run `xo` when something is changed in js files or prevent the tests from running when `.md` files are changed.

Fixes https://github.com/twbs/rfs/issues/149

### CODE REVIEW

**Comment by XhmikosR** [comment]
Maybe we should set it up like you said in this PR? Or you want to tackle this later?

**Comment by MartijnCuppens** [comment]
Lefthook doesn't behave like I would expect, looking into that

The failing tests are caused by changes in my package lockfile which I haven't pushed yet

**Comment by XhmikosR** [comment]
It doesn't seem to work good here.

Even though I modified postcss.js and lint failed, the commit proceeded just fine. Also, it does seem slow like the previous solution.

**Comment by MartijnCuppens** [comment]
@XhmikosR, I've split the hooks now. It's also possible to pass a variable to mocha if only a specific style needs to be checked.

Not sure if we should run things in parallel?

**Comment by XhmikosR** [comment]
Also, it seems something runs twice. This is from my small test:

```
RUNNING HOOKS GROUP: pre-commit

  EXECUTE > lint-js
(SKIP. NO FILES FOR INSPECTING)

  EXECUTE > lint-less
(SKIP. NO FILES FOR INSPECTING)

  EXECUTE > lint-sass
(SKIP. NO FILES FOR INSPECTING)

  EXECUTE > test-all
(SKIP. NO FILES FOR INSPECTING)

  EXECUTE > test-less
(SKIP. NO FILES FOR INSPECTING)

  EXECUTE > test-postcss
(SKIP. NO FILES FOR INSPECTING)

  EXECUTE > test-sass
(SKIP. NO FILES FOR INSPECTING)

  EXECUTE > test-stylus
(SKIP. NO FILES FOR INSPECTING)

SUMMARY: (SKIP EMPTY)

> rfs@8.0.4 stylelint-sass C:\Users\xmr\Desktop\rfs
> stylelint "**/*.scss" "**/*.sass" --cache --cache-location node_modules/.cache/stylelint


> rfs@8.0.4 xo C:\Users\xmr\Desktop\rfs
> xo


> rfs@8.0.4 stylelint-less C:\Users\xmr\Desktop\rfs
> stylelint "**/*.less" --cache --cache-location node_modules/.cache/stylelint


> rfs@8.0.4 mocha-less C:\Users\xmr\Desktop\rfs
> mocha --styles=Less


> rfs@8.0.4 test C:\Users\xmr\Desktop\rfs
> npm run lint && npm run mocha


> rfs@8.0.4 mocha-postcss C:\Users\xmr\Desktop\rfs
> mocha --styles=PostCSS


> rfs@8.0.4 mocha-sass C:\Users\xmr\Desktop\rfs
> mocha --styles=Sass


> rfs@8.0.4 mocha-stylus C:\Users\xmr\Desktop\rfs
> mocha --styles=Stylus



  Less


  Sass


  PostCSS


  Stylus
    √ Default build (350ms)
    √ Default build (235ms)

> rfs@8.0.4 lint C:\Users\xmr\Desktop\rfs
> npm-run-all --parallel xo stylelint

    √ Disable responsive font size (62ms)
    √ Disable responsive font size (71ms)
    √ Default build (146ms)
    √ Disable responsive font size
    √ Disabled class (86ms)
    √ Disabled class (148ms)
    √ Disabled class (79ms)
    √ Enable class (87ms)
    √ Change breakpoint unit to em (62ms)
    √ Enable class (95ms)
    √ Enable class (138ms)
    √ Change breakpoint unit to em (55ms)
    √ Default build (391ms)
    √ Change base font size (61ms)
    √ Change font size unit (60ms)
    √ Change base font size (72ms)
    √ Disable responsive font size (72ms)
    √ Change breakpoint unit to em (152ms)
    √ Change font size unit
    √ Enable two dimensional (92ms)
    √ Disabled class (106ms)
    √ Go loco with the config
    √ Enable two dimensional (72ms)
    √ Include mixins multiple times (52ms)


  10 passing (845ms)

    √ Go loco with the config (55ms)
    √ Change base font size (180ms)
    √ Enable class (97ms)
    √ Include mixins multiple times (68ms)


  10 passing (752ms)


  postcss.js:10:1
  ×  10:1  More than 1 blank line not allowed.  no-multiple-empty-lines

  1 error
    √ Change font size unit (90ms)
    √ Change breakpoint unit to em (89ms)
    √ Enable two dimensional (80ms)
    √ Change base font size (64ms)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rfs@8.0.4 xo: `xo`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rfs@8.0.4 xo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xmr\AppData\Roaming\npm-cache\_logs\2019-08-06T14_33_14_193Z-debug.log
    √ Change font size unit (55ms)
    √ Go loco with the config (72ms)
    √ Enable two dimensional (55ms)
    √ Include mixins multiple times (98ms)


  10 passing (1s)

    √ Go loco with the config (69ms)
    √ Include mixins multiple times (42ms)


  10 passing (1s)


> rfs@8.0.4 xo C:\Users\xmr\Desktop\rfs
> xo


> rfs@8.0.4 stylelint C:\Users\xmr\Desktop\rfs
> npm-run-all stylelint-less stylelint-sass


> rfs@8.0.4 stylelint-less C:\Users\xmr\Desktop\rfs
> stylelint "**/*.less" --cache --cache-location node_modules/.cache/stylelint


> rfs@8.0.4 stylelint-sass C:\Users\xmr\Desktop\rfs
> stylelint "**/*.scss" "**/*.sass" --cache --cache-location node_modules/.cache/stylelint


  postcss.js:10:1
  ×  10:1  More than 1 blank line not allowed.  no-multiple-empty-lines

  1 error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rfs@8.0.4 xo: `xo`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rfs@8.0.4 xo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xmr\AppData\Roaming\npm-cache\_logs\2019-08-06T14_33_16_238Z-debug.log
ERROR: "xo" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rfs@8.0.4 lint: `npm-run-all --parallel xo stylelint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rfs@8.0.4 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xmr\AppData\Roaming\npm-cache\_logs\2019-08-06T14_33_16_387Z-debug.log
npm ERR! Test failed.  See above for more details.
[lefthook 783ddbe] test
 1 file changed, 1 insertion(+)

Success (7984 ms @ 06/08/2019 17:33:16)
```

**Comment by MartijnCuppens** [comment]
Lefthook seemed to slow things down if we're doing changes in different files. Gonna ditch the idea of using git hooks in favor of CircleCI tests.

**Pull request closed without merging**
