### PR TITLE
Remove semicolon

### PR DESCRIPTION
**Pull request by MartijnCuppens**
`.sass` and `.styl` don't need the semicolon.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Why don't they need it?

**Comment by MartijnCuppens** [comment]
It's just the syntax

**Comment by XhmikosR** [comment]
I don't get it. What language is this whole snippet written in?

**Comment by MartijnCuppens** [comment]
I split the examples and reordered them in the same order as the examples above.

**Pull request merged**
